title: Activate Channels and change state to ready
description: This example shows how to log in, activate channels and change state using the Workspace API
categories: 
  - workspace
displayName: Node.Js
