---
ruby:
    displayName: Ruby
    steps:
        - file: "ruby/script.rb"
          highlight: "0-100"
        - file: "ruby/script.rb"
          highlight: "5-15"
        - file: "ruby/script.rb"
          highlight: "17-21"
nodejs:
    displayName: NodeJS
    steps:
        - file: "nodejs/script.js"
          highlight: "0-100"
        - file: "nodejs/script.js"
          highlight: "20-28"
        - file: "nodejs/script.js"
          highlight: "3-18"
powershell:
    displayName: PowerShell
    steps:
        - file: "powershell/script.ps1"
          highlight: "0-100"
        - file: "powershell/script.ps1"
          highlight: "1-7"
        - file: "powershell/script.ps1"
          highlight: "8-12"
python:
    displayName: Python
    steps:
        - file: "python/script.py"
          highlight: "0-54"
        - file: "python/script.py"
          highlight: "7-22"
        - file: "python/script.py"
          highlight: "31-52"
