title: Create user using Provisioning API
description: description
categories: 
  - provisioning
displayName: NodeJS
steps:
  - file: "main.js"
    highlight: "0-43"
  - file: "main.js"
    highlight: "3-8"
  - file: "main.js"
    highlight: "10-10"
  - file: "main.js"
    highlight: "11-19"
  - file: "main.js"
    highlight: "20-22"
  - file: "main.js"
    highlight: "23-38"
  - file: "main.js"
    highlight: "40-40"
