---
oauth-implicit:
    title: OAuth Implicit Grant Login Flow
    description: Implicit grant login without a client library.
    categories:
        - OAuth
oauth-client-credentials:
    title: OAuth Client Credentials Login Flow
    description: Client credentials grant login without a client library.
    categories:
        - OAuth
oauth-auth-code:
    title: OAuth Authorization Code Grant Flow
    description: Authorization code grant login without a client library.
    categories:
        - OAuth
