title: Get Users Asynchronously
description: This tutorial shows you how to use the [Provisioning Client Library](/client-libraries/provisioning/) to search for users with given properties and have the results retuned asynchronously with CometD.
categories: 
  - provisioning
displayName: NodeJS