title: Conference Call using the Workspace API
description: This example shows you how to convert to a conference call with a consultant using the two step process.
categories: 
  - workspace
displayName: Node.Js
