title: Basic Call Control
description: This example shows you how to answer an incomming call, hold it, retrieve it, and then hang up using CometD events.
categories: 
  - workspace
displayName: Java
