title: Get Estimated Wait Time (EWT) Tutorial
description: This Tutorial shows you how to use GES EWT API to get the Estimated Wait Time (EWT) for agent availability.
categories: 
  - GES
displayName: Node.Js
