title: Get Estimated Wait Time (EWT) Tutorial
description: This Tutorial shows you how to use Estimated Wait Time (EWT) API to get the Estimated Wait Time for agent availability.
categories: 
  - callback
displayName: Node.Js
