title: Work with subscriptions
description: This tutorial shows you how to use the [Statistics Client Library](/client-libraries/statistics/) to subscribe to a set of statistics and get notifications about those statistics.
categories: 
  - statistics
displayName: Node.Js