title: Import File
description: This tutorial shows you how to use the [Provisioning Client Library](/client-libraries/provisioning/) import a csv file, get the export status and stop the import.
categories: 
  - provisioning
displayName: NodeJS