title: Transfer Call using the Workspace API
description: This example shows you how to transfer a call to a consultant using the two step transfer process.
categories: 
  - workspace
displayName: Java
