title: Get current session using Workspace API
description: This example shows how to log in and get a current session information using the Workspace API
categories: 
  - workspace
displayName: Java
