title: Office Hours Open For Time Tutorial
description: This Tutorial shows you how to use Office Hours API to get information on how long the office will remain open for so that callbacks can be scheduled appropriately.
categories: 
  - callback
displayName: Node.Js
