title: Create a user
description: This tutorial shows you how to use the [Provisioning Client Library](https://developer.genhtcc.com/api/client-libraries/provisioning/) to create a user.
categories: 
  - provisioning
displayName: Java