title: Retrieving current values of statistic without subscription
description: This tutorial will show how to peek current values of statistics without subscriptions
categories: 
  - statistics
displayName: Java
